import { Config } from "svgo";

export const svgoOptions: Config = {
    // multipass: true,
    // full: true,

    plugins: [
        "removeDoctype",
        "removeXMLProcInst",
        "removeComments",
        "removeMetadata",
        // "removeXMLNS",
        "removeEditorsNSData",
        "cleanupAttrs",
        "inlineStyles",
        "minifyStyles",
        "convertStyleToAttrs",
        "cleanupIds",
        // "prefixIds",
        // "removeRasterImages",
        "removeUselessDefs",
        "cleanupNumericValues",
        // "cleanupListOfValues",
        "convertColors",
        "removeUnknownsAndDefaults",
        "removeNonInheritableGroupAttrs",
        "removeUselessStrokeAndFill",
        // "removeViewBox",
        "cleanupEnableBackground",
        "removeHiddenElems",
        "removeEmptyText",
        "convertShapeToPath",
        "convertEllipseToCircle",
        "moveElemsAttrsToGroup",
        "moveGroupAttrsToElems",
        "collapseGroups",
        "convertPathData",
        "convertTransform",
        "removeEmptyAttrs",
        "removeEmptyContainers",
        "mergePaths",
        "removeUnusedNS",
        // "sortAttrs",
        "sortDefsChildren",
        // "removeTitle",
        "removeDesc",
        "removeDimensions"
        // "removeAttrs",
        // "removeAttributesBySelector",
        // "removeElementsByAttr",
        // "addClassesToSVGElement",
        // "removeStyleElement",
        // "removeScriptElement",
        // "addAttributesToSVGElement",
        // "removeOffCanvasPaths",
        // "reusePaths",
    ],

    // js2svg: {
    //     pretty: true,
    //     indent: 4
    // }
};
