/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UqFooter {}
}

declare global {


  interface HTMLUqFooterElement extends Components.UqFooter, HTMLStencilElement {}
  var HTMLUqFooterElement: {
    prototype: HTMLUqFooterElement;
    new (): HTMLUqFooterElement;
  };
  interface HTMLElementTagNameMap {
    'uq-footer': HTMLUqFooterElement;
  }
}

declare namespace LocalJSX {
  interface UqFooter {}

  interface IntrinsicElements {
    'uq-footer': UqFooter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'uq-footer': LocalJSX.UqFooter & JSXBase.HTMLAttributes<HTMLUqFooterElement>;
    }
  }
}


