// Typescript types for consumers to use.

// This autogenerated type only permits valid icon classes to be specified.
declare export { type IconCode } from './_build/_icons.d.ts';

// Properly type the icon catalogue.
declare const catalogue: {
  name: string;
  category: string;
}[];
export default catalogue;
