/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UqHeader {
    'name': string;
    'sticky': boolean;
  }
}

declare global {


  interface HTMLUqHeaderElement extends Components.UqHeader, HTMLStencilElement {}
  var HTMLUqHeaderElement: {
    prototype: HTMLUqHeaderElement;
    new (): HTMLUqHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'uq-header': HTMLUqHeaderElement;
  }
}

declare namespace LocalJSX {
  interface UqHeader {
    'name'?: string;
    'sticky'?: boolean;
  }

  interface IntrinsicElements {
    'uq-header': UqHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'uq-header': LocalJSX.UqHeader & JSXBase.HTMLAttributes<HTMLUqHeaderElement>;
    }
  }
}


