name: Visual Regression Testing and preview environment

on:
  push:
    branches:
      - 'master'
      - 'beta'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps and build
        run: |
          npm ci
          npx lerna bootstrap --no-ci

      - name: Workaround for detached HEAD
        # Workaround for Detached HEAD https://github.com/reg-viz/reg-suit#workaround-for-detached-head
        run: |
          git checkout "${GITHUB_REF:11}"

      - name: Build Storybook
        run: |
          npm run build-storybook
        working-directory: packages/storybook-html/

      - name: Serve Storybook
        run: |
          npx http-server storybook-static --port 6006 &
        working-directory: packages/storybook-html/

      - name: Create screenshots
        run: |
          npm run update-screenshots

      - name: Run visual regression
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          UQDS_PERSONAL_ACCESS_TOKEN: ${{ secrets.UQDS_PERSONAL_ACCESS_TOKEN }}
        run: |
          npm run reg-suit run --update-screenshots

      - name: Sync to preview environment
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: uq-ds-regsuit
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'packages/storybook-html/storybook-static'
          DEST_DIR: storybook-preview/${{ github.run_id }}

      - name: Add link to storybook preview in comments
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.UQDS_PERSONAL_ACCESS_TOKEN }}
          header: preview
          message: |
            Storybook preview https://uq-ds-regsuit.s3.amazonaws.com/storybook-preview/${{ github.run_id }}/index.html

